### ISSUE TITLE
Release notes / changelog?

### ISSUE THREAD

**Issue by rayshan** [google/traceur-compiler#1264]
Hi, are they available besides the commit history?

**Comment by jmm** [comment]
Is there some effective way for searching for that group for these announcements, like if I just want to find a summary of significant changes between 2 releases?

**Comment by Ashwell** [comment]
@jmm I end up looking at github's compare page from one tagged commit to another, this is what it would look like for 0.0.79 to 0.0.81 https://github.com/google/traceur-compiler/compare/6771d54...5f4c06b

**Comment by jmm** [comment]
@Ashwell Thanks, it's just that there's a great deal of implementation-detail noise in there.

**Comment by Ashwell** [comment]
@jmm True, I typically don't use that to look through code, just commit messages which are typically pretty good and giving hints about changes. Not an end all be all solution for sure.

**Comment by pornel** [comment]
I'd appreciate a dedicated changelog. Newsgroup has other posts I'm not interested in, and Google Groups is not a nice interface.

**Comment by mickeyvip** [comment]
+1 for changelog
