### ISSUE TITLE
assertObject: where is it defined?

### ISSUE THREAD

**Issue by chcokr** [google/traceur-compiler#1281]
Hi,

I recently updated to version 0.0.58. I use Traceur to parse Node.js modules. Ever since the update, whenever I use object/array destructuring I keep seeing $traceurRuntime.assertObject in my compiled codes, whose definition I can't find anywhere in the compiled codes. Where is it defined?

**Comment by sid0818** [comment]
no  my compiled code and runtime library are in sync are you sure we dont need to add anymore packages other than traceur?

**Comment by arv** [comment]
Are you including traceur-runtine.js?

**Comment by sid0818** [comment]
yes I can share my package.json,bower.json and grunt task


![bower](https://cloud.githubusercontent.com/assets/9442576/9705684/9d69d14c-54ea-11e5-8e5e-71291080a017.PNG)

**Comment by sid0818** [comment]
Thanks @arv for getting back. Can you pull request from this link https://github.com/sid0818/Ecma6ToEcma5?
