### ISSUE TITLE
Support `this module`

### ISSUE THREAD

**Issue by guybedford** [google/traceur-compiler#1328]
I believe the current proposal is to import meta with:

```javascript
import { name } from this module;
```

The nice thing about this syntax, is that it can also transpile into AMD and CommonJS actually using their variants of this pattern.

It would be great to start prototyping with it at some point.

**Comment by guybedford** [comment]
There still is no spec for this to be implemented to. As soon as the spec exists, it can be considered.

**Comment by kavi87** [comment]
Any news on this ? Passing contextual configuration to modules would be very interesting.
