### ISSUE TITLE
Traceur may produce `yield` in generator output in conjunction with block-level bindings

### ISSUE THREAD

**Issue by mnieper** [google/traceur-compiler#1379]
Let us be given the file `test.js`:

    function  *f() {
      while (true) {
        let a;
        yield b(() => a);
      }
    }

Running `traceur --experimental test.js --out out.js` yields the following file `out.js`:

    System.register("test", [], function() {
      "use strict";
      var $__1 = $traceurRuntime.initGeneratorFunction(f);
      var __moduleName = "test";
      function f() {
        var $__0;
        return $traceurRuntime.createGeneratorInstance(function($ctx) {
          while (true)
            switch ($ctx.state) {
              case 0:
                $__0 = function() {
                  var a;
                  yield b((function() {
                    return a;
                  }));
                };
                while (true) {
                  $__0();
                }
                $ctx.state = -2;
                break;
              default:
                return $ctx.end();
            }
        }, $__1, this);
      }
      return {};
    });
    System.get("test" + '');

This is clearly a bug as there shouldn't be any `yield` in the output.

**Comment by arv** [comment]
We probably need to generate a generator instead of a function and then use a `yield*` somehow. It gets complicated...

**Comment by mnieper** [comment]
@arv Thinking of it, this sounds plausible. The same issue will be in the InnerForOnTransformer as soon as async generators are being implemented. The inner function, which is currently an async function, will have to become an async generator.

**Comment by arv** [comment]
Other options is to change how we do block bindings. Right now we enclose the whole block in an IIFE. We could do something more localized.

Given:

```js
while (true) {
  let a;
  b(() => a)
}
```

Today generates:

```js
var $__0 = function() {
  var a;
  b((function() {
    return a;
  }));
};
while (true) {
  $__0();
}
```

We could probably do something like:

```js
var $__0 = function(a) {
  return () => a;
};
while (true) {
  var a = undefined;
  b( $__0(a));
}
```

In other words, capture the free variables in the closure and wrap them in another closure.

**Comment by mnieper** [comment]
@arv Your last idea

```javascript
var $__0 = function(a) {
  return () => a;
};
while (true) {
  var a = undefined;
  b($__0(a));
}
```

seems to be hard to implement correctly. If the original code was

```javascript
while (true) {
  let a;
  b(() => a)
  a = 1;
}
```

a translation like

```javascript
var $__0 = function(a) {
  return () => a;
};
while (true) {
  var a = undefined;
  b($__0(a));
  a = 1
}
```

would be wrong.
