### ISSUE TITLE
Write operation stalling

### ISSUE THREAD

**Issue by guybedford** [google/traceur-compiler#1596]
The following file - https://github.com/Leaflet/Leaflet/blob/master/debug/vector/route.js is stalling Traceur's write operation somehow.

The parse runs in under a second, but the write ends up spinning CPU and never completing.

**Comment by arv** [comment]
@guybedford Not sure... I've been away for a few weeks.

@johnjbarton Did you push to npm over the holidays?

**Comment by johnjbarton** [comment]
Sorry forgot about this request. I can do it tomorrow.

**Comment by johnjbarton** [comment]
done

On Sun, Jan 11, 2015 at 11:21 AM, John J Barton <johnjbarton@johnjbarton.com

**Comment by trusktr** [comment]
It's still taking long. I'm on 0.0.81. I'll leave it running and see how long it takes.

**Comment by trusktr** [comment]
It took 6m 27s to install Leaflet with jspm!
