### ISSUE TITLE
Using .ec6 as file extension for ECMA 6 source codes

### ISSUE THREAD

**Issue by hanifbbz** [google/traceur-compiler#1609]
When compiling CoffeeScript files from `.cofee` to `.js` files, it's clear that we are compiling from one language to another.

The changes suggested in ECMA 6 are so huge that it's like a new programming language. It is indeed a superset of Javascript but ECMA 6 source code cannot run directly in the majority of the browsers that are shipped until today (mostly the embedded browsers that have been shipped into millions of TVs, game consoles, etc.)

Even reading ECMA 6 code requires skills that traditional Javascript developers need to learn (the learning curve isn't as steep of learning a whole new language though, but almost).

So how about keeping the old "ECMA 5" Javascript code with `.js` extension and start using `.ec6` for ECMA 6 code?

This makes the satus quo Javascript code future and backward compatible:

**Future compatibility**

When ECMA 7 (or 8 or whatever) lands in the browsers, you can easily spot those source files by their extensions: `.ec7`, `.ec8`, etc. Which means if a project needs to run on a browser that supports only good old ECMA 5, these `.ecX` files need to be "compiled" to the `.js` format.

**Backwards compatibility**

Without touching the `.js` files a project can compile its current `.ec6` files into ECMA 5 `.js` files with the same name (but different extensions). When the project is being shipped to older browsers, the ECMA 6 files are not deployed and instead their corresponding `.js` files are deployed. For browsers that support ECMA 6, the `.ec6` files can be deployed directly.

**What can be done in Traceur?**

This is more of a convention than a syntactic change. Currently it is possible to have Traceur produce a file with a desirable extension but it's not the standard behaviour. I am suggesting that through documentation and convention we start this convention.

Javascript is gradually being referenced as "ECMA 6". So why not using a different file extension that makes it clear while keeping the good old Javascrip assets and projects use the `.js` file extension?

**Comment by josdejong** [comment]
I agree with @zandaqo:

> If one needs to distinguish JS versions in file names, I would suggest adding suffixes to names, for example, .es5.js or .es6.js.

But maybe it should be the opposite: 
- By default, just name your source files `*.js` and use *any* brand new features at your disposal. 
- When distributing your code, alongside bundled and minified `*.min.js` files, you could too generate an ES5 compatible build of your code and name it `*.es5.js`.
After a couple of years, the `*.es5.js` files will become redundant, and you can just drop this build step from your build script and delete the ES5 file. No need to adjust your source code.

**Comment by arv** [comment]
Traceur does not care about the file extension. Our test harness cares but that is only because we need to test certain things in Module vs Script.
