### ISSUE TITLE
traceur-runtime.js - TypeError: Attempted to assign to readonly property.

### ISSUE THREAD

**Issue by marani** [google/traceur-compiler#1611]
I was running gulp test on Phantom browser with Karma 
```
INFO [karma]: Karma v0.12.28 server started at http://localhost:9876/
INFO [launcher]: Starting browser PhantomJS
INFO [PhantomJS 1.9.8 (Linux)]: Connected on socket -uIdf2Xu5QXyITLWF5iD with id 99635568
PhantomJS 1.9.8 (Linux) ERROR
  TypeError: Attempted to assign to readonly property.
  at /home/marani/gga/ft-app-path/test/t2/bower_components/traceur-runtime/traceur-runtime.js:908



/home/marani/gga/ft-app-path/test/t2/gulp/unit-tests.js:30
      throw err;
            ^
Error in plugin 'gulp-karma'
karma exited with code 1
    at done (/home/marani/gga/ft-app-path/generator-gulp-angular/test/deps/node_modules/gulp-karma/index.js:56:30)
    at ChildProcess.<anonymous> (/home/marani/gga/ft-app-path/generator-gulp-angular/test/deps/node_modules/gulp-karma/index.js:82:7)
    at ChildProcess.emit (events.js:98:17)
    at Process.ChildProcess._handle.onexit (child_process.js:810:12)
marani@lorien:~/gga/ft-app-path/test/t2$ 
```

This is line 908 of traceur-runtime.js
`          ex.stack = evaled.join('\n');`

More Info:
* traceur-runtime version: 0.0.74, 0.0.79
* PhantomJS 1.9.8
* Ubuntu 12.04
* The preprocessing tasks includes ngAnnotate and Traceur. But this seems like traceur-runtime's error rather than a normal test fail.

Reproduce:
- `npm install-g generator-gulp-angular@0.8.1` 
- `yo gulp-angular` & select the settings below:
 - angular 1.3
 - all modules
 - jquery 2
 - restangular
 - ui router
 - bootstrap
 - ui bootstrap
 - node-sass
 - traceur
 - no html preprocessor
- `gulp test`

**Comment by rootical** [comment]
Two months passed, were there any able to fix the issue?

**Comment by arv** [comment]
I think this was fixed by #1612 

@johnjbarton

**Comment by johnjbarton** [comment]
#1612 was just a guess and we did not land it.  @rootical you could try that patch and see if it fixes the issue.  I'll try to revive it.

Or please post a reduced test case, that is one that includes a test source but only uses Traceur.

**Comment by rootical** [comment]
@johnjbarton, Unfortunately it didn't fixed the issue.
Switched to babel
