### ISSUE TITLE
'this' is incorrectly translated in nested method

### ISSUE THREAD

**Issue by mhelvens** [google/traceur-compiler#1631]
Here is a scenario in which `this` is incorrectly translated to `$__0`.
```JavaScript
() => {
 this;                             // OK
  ({
    method1: function () { this }, // OK
    method2() { this }             // BUG
  });
};
```
is translated to
```JavaScript
var $__0 = this;
(function() {
  $__0;
  ({
    method1: function() { this },
    method2: function() { $__0 }
  });
});
```
This happens under the following circumstances:

  1. Inside a 'method-notation' method in an object literal,
  2. which is located inside a fat-arrow function,
  3. which contains other occurrences of `this` that *do* need to be translated.

Here is a [link](https://google.github.io/traceur-compiler/demo/repl.html#()%3D%3E%7B%0A%20this%3B%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%2F%2F%20OK%0A%20%20(%7B%0A%20%20%20%20method1%3A%20function%20()%20%7B%20this%20%7D%2C%20%2F%2F%20OK%0A%20%20%20%20method2()%20%7B%20this%20%7D%20%20%20%20%20%20%20%20%20%20%20%20%20%2F%2F%20BUG%0A%20%20%7D)%3B%0A%7D%3B%0A%20%20%0A%0A%0A%0A%0A%0A%0A%0A) to this example in the online editor.

**Comment by arv** [comment]
We have the same problem with arguments. `alphaRenameThisAndArguments` needs to not enter methods.

**Comment by mhelvens** [comment]
Thanks for the quick fix!
