### ISSUE TITLE
Use await with superagent HTTP client

### ISSUE THREAD

**Issue by shirk3y** [google/traceur-compiler#1633]
Hi, I want to use async functions to fetch some web pages in synchronous-style. I'm using [superagent library](https://github.com/visionmedia/superagent), and trying to convert request to promise and await for the response, but `after` is never printed. Please somebody help me with this. Code below:

    var superagent = require('superagent')
    var request = superagent('GET', 'http://nodejs.org');

    function promisify(r) {
        return new Promise((resolve) => {
            r.end(resolve);
        });
    }

    (async function() {
        console.log('before');
        response = await promisify(request);
        console.log('after', response);
    })();

**Comment by arv** [comment]
I'm not sure you are using the superagent API correctly. Try adding a try/catch since nothing is logged by default:

```js
(async function() {
  console.log('before');
  try {
    response = await promisify(request);
    console.log('after', response);
  } catch (ex) {
    console.error(ex);
  }
})();
```

**Comment by shirk3y** [comment]
Thanks @arv !
Indeed, there was an `ReferenceError` that response is not defined (i forgot to use `var`). For the future, is there any way to turn on logging by default?

**Comment by arv** [comment]
Chrome and Firefox developer tools should log rejected promises.
