### ISSUE TITLE
Lets leak through eval

### ISSUE THREAD

**Issue by tolmasky** [google/traceur-compiler#1636]
If ES6 land:

    if (true)
    {
        let x = 9;
        console.log(eval("x"));
    }
    console.log(eval("x"));

You expect to see 9, then an Error.

However, in traceur land:

You see 9 twice. Generating something like this would save it:

    if (true)
    (function() { var x = 9; console.log(eval("x")); })()

    console.log(eval("x"));

**Comment by arv** [comment]
We don't fully support `eval`. It would require compiling the string at runtime, knowing the context etc.

**Comment by tolmasky** [comment]
I can certainly understand not supporting eval, but this case isn't necessarily tied to eval, but rather the fact that semantically the variable *is* exposed to the entire scope. (As such it is equally exposed to new Function("console.log(x)")). The solution doesn't necessarily require computing anything at runtime either, just properly protecting the variable (in the new function approach I used above no runtime knowledge is needed and the variable is still properly protected).

**Comment by UltCombo** [comment]
@tolmasky actually, this is way more complicated than it seems.

Traceur only creates a new scope when necessary, it prefers to rename variables instead of introducing new scopes whenever possible.

Take, for instance, the following code:

```js
let x = 1;
{
  let x = 2;
  console.log( eval('x') );
}
```

Is currently transpiled to:

```js
$traceurRuntime.ModuleStore.getAnonymousModule(function() {
  "use strict";
  var x = 1;
  {
    var x$__0 = 2;
    console.log(eval('x')); // `x` should be `x$__0`
  }
  return {};
});
```

This can't be handled properly unless Traceur parses the string at runtime and has context exposed to this runtime compiling.

**Comment by UltCombo** [comment]
Oh, and of course, the `eval`'ed string in the previous comment *could* technically be parsed and compiled ahead of time, but that's not always the case. E.g.:

```js
let x = 1;
{
  let x = '() => ';
  if (2 > 1) x += 'x;';
  console.log( eval(x) );
}
```

This requires runtime compiling with available scope/context data as @arv commented.

**Comment by tolmasky** [comment]
@UltCombo I'm not sure why my function-wrapping proposal seems to be being ignored in favor of these name mangling approaches which I completely agree would be incredibly complex. If let'ed blocks were simply wrapped in called anonymous functions *I think* it would handle all this without any need for pre-computation:

block with let -> wrap in anonymous function:

    let x = 1;
    {
         let x = '() => ';
         if (2 > 1) x += 'x;';
         console.log( eval(x) );
    }

becomes:

   (function()
   {
      var x = 1;
      (function() {
       {
           var x = '() => ';
           if (2 > 1) x += 'x;';
           console.log( eval(x) );
        }
        })();
    })()

That would work completely fine with expected behavior (if eval does the proper translation of () => x to (function() { return x }) ). In fact, calling eval(x)() would also work correctly. Again this works because there is no name mangling taking place at all, we are relying on actual scope to hide variables.

**Comment by UltCombo** [comment]
@tolmasky I believe the name mangling is mainly for performance reasons.

Creating new function scopes for blocks has some edge cases I believe, for example:

```js
let x = 1;
{
  let x = 2;
  var y = 2;
  console.log( eval('x') );
}
console.log(y); // should be 2
```

That's one of the reasons blocks can't just be converted to function scopes. There are probably more edge cases that I'm overlooking.

Not a long time ago, Traceur converted all block scoping (`let`, `const`) to `try/catch` blocks in order to better emulate block scoping, but that was terrible for performance. Hence the identifiers mangling was introduced to solve this performance bottleneck.

**Comment by tolmasky** [comment]
The var case should be easily handled by doing the hoisting before the let scoping step:

Initial:

```javascript
let x = 1;
{
  let x = 2;
  var y = 2;
  console.log( eval('x') );
}
console.log(y); // should be 2
```

1. Hoist per JavaScript spec:
```javascript
let x = 1;
var y;
{
  let x = 2;
  y = 2;
  console.log( eval('x') );
}
console.log(y); // should be 2
```

2. Scope:

```javascript
(function()
{
var x = 1;
var y;
(function() {
{
  var x = 2;
  y = 2;
  console.log( eval('x') );
}
})()
console.log(y); // should be 2
})()
```

Now, if the argument against block scoping is performance, then that is certainly a reasonable tradeoff to discuss (although I'm pretty sure try/catches have much more onerous performance implications than simple anonymous functions). However, I feel that the transformation itself is not actually complex and certainly leads to less surprises (which was the theoretical original reason this bug was closed).

**Comment by tolmasky** [comment]
I'd also like to point out that this bug that traceur currently does have ( https://github.com/6to5/6to5/issues/510 ) would trivially never exist in tracer land with the function approach:

```javascript
for (let i = 0; i< 10; ++i)
{
  for (let i = 0; i < 10; ++i)
  {
    for (let i = 0; i < 10; ++i)
    {
      console.log(i)
    }
  } 
}
```

Currently gets compiled to:

```javascript
$traceurRuntime.ModuleStore.getAnonymousModule(function() {
  "use strict";
  for (var i = 0; i < 10; ++i) {
    for (var i$__0 = 0; i$__0 < 10; ++i$__0) {
      for (var i$__1 = 0; i$__0 < 10; ++i$__0) {
        console.log(i$__0); //should be i$__1
      }
    }
  }
  return {};
});
//# sourceURL=traceured.js
```

Again, as a result of pretty complex name mangling. (Under my proposal this would just become:

```javascript
(function() {for (let i = 0; i< 10; ++i)
{
function() {
  for (let i = 0; i < 10; ++i)
  {
(function()
    for (let i = 0; i < 10; ++i)
    {
      console.log(i)
    }
})()
  } 
})()
} })()
```

**Comment by domenic** [comment]
@tolmasky I'd encourage you to write a patch and see if you can make it pass all of Traceur's existing tests.

**Comment by tolmasky** [comment]
@domenic I'd be happy to do that but was curious if this had already been brought up and actually shot down due to performance reasons (as the try/catch system was). If it had already been discussed then no need to do it, I was just bring up the technical feasibility (and I believe the technical benefits) since it the initial reasons for closing the bug seemed to be based on that.

**Comment by UltCombo** [comment]
Yes, the specific use case I've shown can be easily addressed by moving the var declarations to the top of their respective scopes, my point is that are most likely other use cases that I'm overlooking -- I'm not quite sure as I've never attempted to write such a transform. Perhaps someone with more experience in the block scope transformations area can enlighten us in what reasons made they choose `try/catch` and identifier mangling over function scopes?

// cc @arv @sebmck @rodyhaddad

**Comment by UltCombo** [comment]
Oh, I just recalled that `continue` and `break` inside of loop blocks were one of the main reasons I believe.

**Comment by tolmasky** [comment]
Ah yeah, those would indeed be fun, returns come into play here too. You’d probably want something like:
 
break -> return [0];
continue -> return [1];
return -> return [2, value]

_r = (function(){ block_with_those_replacements })())
if (_r && _r[0] === 0) break;
if (_r && _r[0] === 1) continue;
if (_r && _r[0] === 2) return _r[1];

**Comment by arv** [comment]
The reason to not IIFEs is performance.

The transformation to always use IIFE is much simpler than what we have now, even with break/continue/return. We use IIFEs for loops that capture a binding so we already have support for break/continue/return.

I'll file a new bug for the loop thing since that is pretty serious.

**Comment by arv** [comment]
#1637 for the for-loop bug.
