### ISSUE TITLE
Traceur/Atscript - annotations vs annotate

### ISSUE THREAD

**Issue by hannahhoward** [google/traceur-compiler#1642]
When Traceur compiles annotations, they become a .annotations property on the object they annotate. However, the AtScript specification, or at least the AtScript Primer, which is the top Google hit when you search for AtScript specification, says the property should be called .annotate:
https://docs.google.com/document/d/11YUzC-1d0V1-Q3V0fQ7KSit97HnZoKVygDxpWzEYW0U/mobilebasic?viewopt=127

Should these be brought into sync in some fashion? Which is correct for AtScript? It's very confusing.

Also, it looks like TypeScript is looking at Annotations based off the .annotate property mentioned in the AtScript primer. https://github.com/Microsoft/TypeScript/issues/1557

**Comment by JeroMiya** [comment]
Thanks for fixing this! As you say, I based it off of the primer.

As an aside, there is some discussion in the referenced TypeScript issue regarding decorators vs. annotations, with some leaning towards decorators. Would anyone on the traceur team care to chime in on that discussion - perhaps explaining why traceur chose annotations over decorators?

**Comment by arv** [comment]
I'm not sure about this. The annotations feature was added by the Angular team. If they want to change the name of the property I'm fine with that but the option name should still be annotations for consistency.

@vojtajina

**Comment by hannahhoward** [comment]
yep I'm just trying to bring it in line with the published docs on AtScript, which I think the Angular team created. Honestly, it's early enough that either is probably fine, just wanted to call attention to the inconsistency. Maybe it makes better sense to just fix the docs.

**Comment by matjaz** [comment]
yeah. The same goes to `parameters` array of arrays vs. [{is, annotate:[]}]

**Comment by caitp** [comment]
It looks like the doc was written by @mhevery, so presumably annotate is correct? (but, a quick grep of the angular2 tree shows `annotations` used quite a lot :()

**Comment by arv** [comment]
I'm going to close this bug until I hear from @mhevery or @IgorMinar.
