### ISSUE TITLE
typeof returns wrong value for symbols

### ISSUE THREAD

**Issue by mvolkmann** [google/traceur-compiler#1645]
let mySym = Symbol('foo');
console.log(typeof mySym); // outputs "object", should be "symbol"

**Comment by johnjbarton** [comment]
Symbols are not on by default 

https://google.github.io/traceur-compiler/demo/repl.html#%2F%2F%20Options%3A%20--symbols%20%0Alet%20mySym%20%3D%20Symbol('foo')%3B%0Aconsole.log(typeof%20mySym)%3B%20%2F%2F%20outputs%20%22object%22%2C%20should%20be%20%22symbol%22
