### ISSUE TITLE
SyntaxError: Cannot use initialiser syntax in a strict mode enumeration.

### ISSUE THREAD

**Issue by errorx666** [google/traceur-compiler#1647]
I'm compiling TypeScript -> ES6 -> JS.

Mobile Safari on iOS 8.1.2 is throwing the following Error: `SyntaxError: Cannot use initialiser syntax in a strict mode enumeration.`

The ES6 code emitted from TypeScript:
```Javascript
var __extends = this.__extends || function (d, b) {
    for (var p in b) if (b.hasOwnProperty(p)) d[p] = b[p];
    function __() { this.constructor = d; }
    __.prototype = b.prototype;
    d.prototype = new __();
};
```

The JavaScript code output from Traceur:
```Javascript
  var __extends = this.__extends || function(d, b) {
    for (var p = void 0 in b)
      if (b.hasOwnProperty(p))
        d[p] = b[p];
    function __() {
      this.constructor = d;
    }
    __.prototype = b.prototype;
    d.prototype = new __();
  };
```

The error occurs on the `for` statement.

**Comment by errorx666** [comment]
I'm compiling TypeScript -> ES6 -> JS.

The ES6 code emitted from TypeScript appears to be as follows:
```Javascript
var __extends = this.__extends || function (d, b) {
    for (var p in b) if (b.hasOwnProperty(p)) d[p] = b[p];
    function __() { this.constructor = d; }
    __.prototype = b.prototype;
    d.prototype = new __();
};
```

**Comment by arv** [comment]
This line of code is problematic:

```js
for (var p = void 0 in b)
```

I'm not sure why we are adding the initializer in the for loop. We should not do that.

**Comment by muzuiget** [comment]
Same here, my site broken in Safari 8, any workaround?

**Comment by errorx666** [comment]
@muzuiget for now, a grunt task to replace " void 0 in " with " in "?

Not the most elegant solution, admittedly.

**Comment by zoe-1** [comment]
Just downloaded the quick start tutorial learned about from Brad Greens twitter post today. 
I was using Safari and got errors:
[Error] ReferenceError: Can't find variable: System
	global code (index.html, line 5)
[Error] SyntaxError: Cannot use initialiser syntax in a strict mode enumeration.
	(anonymous function) (es6-shim.js, line 4941)
Hope this helps.

**Comment by johnjbarton** [comment]
@zoe-1 Please open a new issue and tell us what file you loaded in to safari, Thanks!

**Comment by zoe-1** [comment]
Ok. Made an issue here:
https://github.com/google/traceur-compiler/issues/1862
