### ISSUE TITLE
Symbol.toString() does not match spec

### ISSUE THREAD

**Issue by johnjbarton** [google/traceur-compiler#1648]
Doesn't this code imply that --symbols must be true? 
```js  
Object.defineProperty(GeneratorFunctionPrototype.prototype, Symbol.iterator,
      nonEnum(function() {
        return this;
      }));
```

**Comment by arv** [comment]
No. The symbol transformation pass is needed to wrap all `object[expr]` in `$traceurRuntime.toPropertyName` as well as handling `typeof symbol`. Even when the symbol option is turned off we allow usage of `Symbol.iterator`.

However, I think we could simplify this further by just using `toString` when symbols are off.

**Comment by johnjbarton** [comment]
We at least  have this problem: we execute our runtime when we compile; the runtime uses `Symbol.iterator` to define `generator[Symbol.iterator]`, calling `Symbol.toString()`.  The definition of `Symbol.toString()` depends upon the new runtime flag `$traceurRuntime.options.symbols` which is changed iff `SymbolTransformer` is run during compiling.  Thus the result of `generator[Symbol.iterator]` is different when the runtime executes vs after the first `transform()` run. 

I'm unsure if this is the problem I am seeing on my branch and I don't know why this bug is not already visible.

**Comment by arv** [comment]
I think I am convinced that we should always use symbol toString. The main reason for that was to prevent people from hijacking the string but I don't think that is important enough to care about. It will allow us to simplify a lot of things which of course is a good thing.

**Comment by johnjbarton** [comment]
I gather you mean we can avoid the run time option here and remove the `!getOption('symbols')` test?
```js
  $defineProperty(Symbol.prototype, 'toString', method(function() {
    var symbolValue = this[symbolDataProperty];
    if (!getOption('symbols'))
      return symbolValue[symbolInternalProperty];
    if (!symbolValue)
      throw TypeError('Conversion from symbol to string');
    var desc = symbolValue[symbolDescriptionProperty];
    if (desc === undefined)
      desc = '';
    return 'Symbol(' + desc + ')';
  }));
```

**Comment by johnjbarton** [comment]
The problem I have is that
```js
Object.defineProperty(GeneratorFunctionPrototype.prototype, Symbol.iterator,
      nonEnum(function() {
        return this;
      }));
```
defines a symbol on `GeneratorFunctionPrototype.prototype` and later we attempt to access the property via `$3[Symbol.iterator]`.  That works fine if `--symbols

**Comment by arv** [comment]
The idea would be to have `Symbol.prototype.toString` return the GUID at all times. It is not correct but it would allow us to skip wrapping all member lookup expressions.

**Comment by johnjbarton** [comment]
I changed the title here, as the outcome of our discussion was a decision to change the code to make it not implement one small aspect of the spec in exchange for simplifying the issues discussed here.
