### ISSUE TITLE
Map on Safari throws error when constructor is passed arguments

### ISSUE THREAD

**Issue by benhughes** [google/traceur-compiler#1650]
After compiling the following with Traceur (using es6ify):

```
var some var = new Map([
      ['key', 'data']
])
```

Safari throws

```
[Error] TypeError: Map constructor does not accept arguments
```

I see from http://kangax.github.io/compat-table/es6/ that Safari does not support this feature of ES6. Are there any plans to polyfill it in Safari?

Traceur version: 0.0.79
Safari version: 8.0.2

**Comment by arv** [comment]
We have a polyfill, so it is just a matter of changing the detection.

**Comment by paulftw** [comment]
+1
This breaks Angular 2.0 in Safari

**Comment by paulftw** [comment]
As a workaround I modified `polyfillMap(...)` - added the following snippet:

```javascript
  if (!global.Map) {
    global.Map = Map;
  } else {
    try {
      new global.Map([['k', 'v']]);
    } catch (e) {
      // Native Map doesn't support constructor arguments (Safari 8 and below).
      global.Map = Map;
    }
  }
```

**Comment by hydrotik** [comment]
+1 Angular 2.0 broken on Safari

**Comment by caitp** [comment]
it works in WebKit Nightly though, or did last I checked =) Just be sure to use WK Nightly during your demos ;)

**Comment by arv** [comment]
I want to fix this... I just haven't had enough time to get it fixed.

1. If the browser has no `Symbol` support use polyfill.
2. If the browser has no `Symbol.iterator` support use polyfill.
3. If `new Set([1]).size !== 1` use polyfill.

Patches welcome.

**Comment by zloirock** [comment]
@arv https://github.com/paulmillr/es6-shim/issues/326#issuecomment-90737758

**Comment by arv** [comment]
@zloirock I don't agree with that list. iterator closing is a abomination. I wish I had been stronger in opposing it at TC39. It requires all your code to be wrapped in a try/catch which is insane.

**Comment by zloirock** [comment]
@arv abomination, but required for compliance with the specification. Wrapper for constructor much better complete replacement of collection.

**Comment by arv** [comment]
@zloirock No doubt. We just have to prioritize things based on importance and this one is very low.

**Comment by paulftw** [comment]
@arv I've posted a workaround earlier, if you are too busy - I don't mind spending some time on a mature pull request. 

Only problem is I have no idea what is considered an acceptable PR for traceur.

Could you point out a similar patch to use as scaffolding? Something small that's been accepted recently, addresses a similar feature, has tests, etc.
I'm aware of CONTRIBUTING.md. 

BTW I'm not sure your test #3 will work though - Map constructor seems to throw an exception if any params are present.

**Comment by arv** [comment]
Yeah 3 needs a try/catch.

This commit might be serve as inspiration: 19512031ddfbd13ab6c21861ed41bda91b087992

Here is where the setup is done: https://github.com/google/traceur-compiler/blob/master/src/runtime/polyfills/Map.js#L195-L209 and similarly for Set.

We might also need to have a way to detect if native Symbols are supported: https://github.com/google/traceur-compiler/blob/master/src/runtime/runtime.js#L462-L473
