### ISSUE TITLE
Spread doesn't work in IE 9

### ISSUE THREAD

**Issue by webbedspace** [google/traceur-compiler#1659]
Noticed this while running Traceur-compiled compat-table tests in IE 9:
![](http://i.imgur.com/wKN7dYn.png)

**Comment by arv** [comment]
it is not clear to me why IE9 would behave differently here? IE9 does not support strict mode so maybe that could be the problem. I need more information.

**Comment by webbedspace** [comment]
Something else:
```
>> $traceurRuntime.toProperty(Symbol.iterator) in Array.prototype 
false 
```

**Comment by guybedford** [comment]
I'm getting the following error in IE9 - 

```
   undefined: 'Float32Array' is undefined in traceur@0.0.82/src/runtime/polyfills/Math.js
```

**Comment by arv** [comment]
The Float32Array case makes a lot of sense because IE9 does not support that. If you need IE9 I would just disable the Math polyfill. IE9 has a few other issues so I'm not sure I would bother with it.

**Comment by guybedford** [comment]
@arv I was under the impression IE9 was a supported browser for Traceur though?

**Comment by arv** [comment]
@guybedford There are definitely cases where IE9 and even IE10 will not have the right semantics for all the features Traceur supports. For example, IE9 has no strict mode (which means unresolved identifiers are not throwing on set) and IE10 has no writable [[Prototype]] (which means no class side inheritance).

**Comment by djindjic** [comment]
it could be worth to handle disabling not supported polyfill(s) in traceur code. in this case traceur doesn't work in ie9 by default and btw it was hard (for me) to find this issue on gooogle.

**Comment by djindjic** [comment]
sorry, one more question. I cant find in docs how to disable math polyfill?

**Comment by arv** [comment]
Maybe this answers your question. https://github.com/google/traceur-compiler/wiki/Building-custom-Traceur-runtimes.

We should probably feature detect Float32Array. I know es6-shim has a solution that works without Float32Array but it is little over hundred of lines.

https://github.com/paulmillr/es6-shim/blob/master/es6-shim.js#L365-L486

**Comment by arv** [comment]
Filed #1703 for dealing with Float32Array.

**Comment by djindjic** [comment]
its a little hard for my mind :D but as I understand you will patch it with some es6-shime code? thanks

**Comment by arv** [comment]
Should be working now.
