### ISSUE TITLE
Runtime as a dependency

### ISSUE THREAD

**Issue by guybedford** [google/traceur-compiler#1667]
I would like to make a first step towards https://github.com/google/traceur-compiler/issues/437, by simply having an option to enable adding a dependency to a custom-named traceur-runtime package, and then having that provide the reference to `$traceurRuntime` instead of a global.

It would be a very simple first PR, that would then lead to enabling splitting into a granular runtime over time with requires like `import { $class } from 'traceur-runtime/class'` when this option is enabled.

It would be useful for the jspm workflow as runtime becomes another module to handle at the bundling level instead of an exception to be magically handled somehow.

Let me know your thoughts, and any implementation ideas then I'll see if I can get together a PR.

**Comment by arv** [comment]
We have too many issues covering this exact thing. Closing this.

See #1628 for a recent discussion and some early work in a branch of mine.
