### ISSUE TITLE
Generator comprehensions

### ISSUE THREAD

**Issue by simonzack** [google/traceur-compiler#1674]
Does traceur support generator comprehensions in the form of

    (x for (x of generateValues()) if (x.color === ‘blue’))

The [language features](https://github.com/google/traceur-compiler/wiki/LanguageFeatures) page uses a different sort of syntax, and the link points to something else in the spec.

**Comment by domenic** [comment]
I believe that is the old syntax that was replaced with the new syntax.

**Comment by simonzack** [comment]
Thanks for the fast reply. Do you know what though? Having some trouble finding it in the spec.

**Comment by UltCombo** [comment]
@simonzack probably because generator comprehensions and array comprehensions were removed from ES6.

**Comment by simonzack** [comment]
Hmm I did find a [thread](https://mail.mozilla.org/pipermail/es-discuss/2014-June/037428.html) discussing it. I guess I'll have to keep on using plain old if's then.
