### ISSUE TITLE
Unnecessary source maps

### ISSUE THREAD

**Issue by simonzack** [google/traceur-compiler#1682]
In my firefox debugger (not sure about chrome), I'm getting extra source maps which contain the following:

`1`:

    if (!$__placeholder__0 || !$__placeholder__1.__esModule)
            $__placeholder__2 = {default: $__placeholder__3}

`.../generated/templateParser/...`:

    return $__placeholder__0

This adds a lot of clutter, is there any option to disable this?

**[EDIT]** related to #1615, apparently a chrome issue too.

**Comment by arv** [comment]
Duplicate
