### ISSUE TITLE
Default `sourceRoot` to `false`

### ISSUE THREAD

**Issue by jmm** [google/traceur-compiler#1696]
In traceur 0.0.83, this:

```js
(new traceur.NodeCompiler({sourceMaps: 'inline'}))
  .compile(';', 'a.js', '/x/y/z.js')
```
Results in `sourceRoot: "/x/y/"` in the source map. What's the rationale for that?

**Comment by johnjbarton** [comment]
The default `sourceRoot` is the output directory.  This makes sense for the common case, where the sources are compiled in to a bundle located in the output directory.

I also think making the sourceRoot option default to `false` would make sense.  Then users who want to deal with sourceRoot can and the rest of us can ignore it ;-)

**Comment by jmm** [comment]
> The default `sourceRoot` is the output directory. This makes sense for the common case, where the sources are compiled in to a bundle located in the output directory.

I don't know how common that case is, and `outputName` may be imaginary anyway. Also, in that case the source map is likely in / next to the bundle, right? So relative `sources` paths would be resolved using the bundle / map file URL as the base anyway, wouldn't they? After recent experience with problems with improper handling of `sourceRoot` in traceur, I'm leery of too much magic. Unless it's very clear that the meaning and application of the properties is well understood and there's a clear advantage to doing the magic (like if people can chime in with compelling reasons for doing this), I think that stuff should be opt-in for now. It's pretty easy to do any path manipulation you need within node, e.g. do this if you want:

```js
compile(src, sourceName, outputName, path.dirname(outputName))`
```

Maybe there's a case for CLI users getting params to opt-in to this kind of thing.

**Comment by johnjbarton** [comment]
>So relative sources paths would be resolved using the bundle / map file URL as the base anyway, wouldn't they?

Yes, exactly.

> I think that stuff should be opt-in for now.

What stuff?

**Comment by jmm** [comment]
> Yes, exactly.

Then why would you need to populate `sourceRoot`?

> What stuff?

Magical values for `sourceRoot`, `sourceName`, etc.

**Comment by johnjbarton** [comment]
I don't know what you want here. Calling things 'magical' does not help me.   I need to know what your issue is.

**Comment by jmm** [comment]
I want `sourceRoot` output to not be any value that I didn't put in unless it's documented how and why it will be altered or automatically generated and it makes sense and I still have some reasonable means to force it to the output value I want. Ditto for other properties like `sourceName`.

**Comment by johnjbarton** [comment]
>I want sourceRoot output to not be any value that I didn't put 

Ok so pass in the `sourceRoot` option and let me know if that fails. 

> Ditto for other properties like sourceName.

See #1695

**Comment by jmm** [comment]
> Ok so pass in the `sourceRoot` option and let me know if that fails.

I already elaborated that it fails in my original post. A value that I didn't put in comes out.
