### ISSUE TITLE
HomeObject should be set at method definition time?

### ISSUE THREAD

**Issue by sebmck** [google/traceur-compiler#1702]
Traceur includes [this](https://github.com/google/traceur-compiler/blob/master/test/feature/Classes/SuperChangeProto.js) test but after checking the spec I can't find where this behaviour is actually defined?

##### [9.2.11 MakeMethod ( F, homeObject) Abstract Operation](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-makemethod)

> The abstract operation MakeMethod with arguments F and homeObject configures F as a method by performing the following steps:
>
> 1. Assert: F is an ECMAScript function object.
> 2. Assert: Type(homeObject ) is either Undefined or Object.
> 3. Set the [[NeedsSuper]] internal slot of F to true.
> 4. **Set the [[HomeObject]] internal slot of F to homeObject.**
> 5. Return NormalCompletion(undefined).

From what I can tell the `[[HomeObject]]` is actually set when the method is defined instead of when evaluating `super`. Am I reading this correctly?

**Comment by arv** [comment]
[[HomeObject]] is set when the method is defined but we still need to walk the [[Prototype]] chain. That same test passes in V8 (if you add 'use strict' and run with --harmony) and should pass in IE Preview

**Comment by sebmck** [comment]
@arv Ah great, just making sure. Thanks!
