### ISSUE TITLE
Feature detect Float32Array in polyfills/Math.js

### ISSUE THREAD

**Issue by arv** [google/traceur-compiler#1703]
We currently break in IE9 which does not have Float32Array.

es6-shim has a solution

https://github.com/paulmillr/es6-shim/blob/master/es6-shim.js#L365-L486

**Comment by arv** [comment]
@ljharb I see your code is MIT. I'm tempted to reuse it here.

**Comment by ljharb** [comment]
It's actually taken from https://github.com/paulmillr/es6-shim/blob/master/es6-shim.js#L351-L352

**Comment by arv** [comment]
I used to sit next to @inexorabletash in SF. Joshua, I assume you have no issues with me reusing that code here as well?

**Comment by inexorabletash** [comment]
Yep, go for it. 

(Maybe double check that it has the latest snapshot of my code, I fixed some edge cases a year or two ago)
