### ISSUE TITLE
Transpile to ES6: throws error

### ISSUE THREAD

**Issue by tbosch** [google/traceur-compiler#1707]
`PureES6Transformer` expects an additional `options` argument, which is not provided by `src/Compiler.js` when it creates it.

See [this repl code](https://google.github.io/traceur-compiler/demo/repl.html#%2F%2F%20Options%3A%20--output-language%3Des6%20%0Aclass%20Test%20%7B%0A%7D).

**Comment by johnjbarton** [comment]
Fixed by 9950495cf575ec2b55d9b136df3fa550ad409517
