### ISSUE TITLE
Safari throws an error when extending HTMLElement

### ISSUE THREAD

**Issue by ycon** [google/traceur-compiler#1709]
`
class MyClass extends HTMLElement {} 
`
Will throw an "Potentially unhandled rejection [2] getProtoParent" error on Safari 8.1

`
typeof HTMLElement
`

Will be an 'object' on Safari (HTMLElementConstructor) and a 'function' on Chrome

**Comment by arv** [comment]
Known old Safari bug.

https://bugs.webkit.org/show_bug.cgi?id=74193

**Comment by arv** [comment]
Extending builtins is not working even when the browser correctly reports `HTMLElement` as a function. The call to `super()` does not work in Traceur.

**Comment by SerkanSipahi** [comment]
Its works see: https://github.com/babel/babel/issues/1548

**Comment by SerkanSipahi** [comment]
Here is an example @ycon:

if (typeof HTMLElement !== 'function'){
    var _HTMLElement = function(){};
    _HTMLElement.prototype = HTMLElement.prototype;
    HTMLElement = _HTMLElement;
}

**Comment by trusktr** [comment]
@SerkanSipahi Thanks! This hack works.

**Comment by SerkanSipahi** [comment]
@trusktr :)
