### ISSUE TITLE
traceur.js unexpected reserved word and bootstrap.js traceur is not defined errors

### ISSUE THREAD

**Issue by jgw96** [google/traceur-compiler#1722]
Every time I try to run my app using traceur I get an unexpected reserved word error from traceur.js and an traceur is not defined error from bootstrap.js. This causes my app to not run.

**Comment by johnjbarton** [comment]
I am unable to see you computer monitor from over here. Thus I have no idea what you mean by your 'app', I can't see the line of source that the error message points to, or what you mean by 'run'.

**Comment by UltCombo** [comment]
Support questions are better asked in the newsgroup.

Also, as JJB mentioned, you are supposed to show a [SSCCE](http://sscce.org/)/[MCVE](http://stackoverflow.com/help/mcve) when reporting bugs/asking support questions.

**Comment by arv** [comment]
Using gihub issues seems fine to me but please provide some more info. What line of code is failing for you?

**Comment by johnjbarton** [comment]
@jgw96 sorry my comment sounds childish. If you have a problem that we can solve we need more info. The bootstrap error is probably just caused by the first error.
