### ISSUE TITLE
--dir option outputs named modules

### ISSUE THREAD

**Issue by guybedford** [google/traceur-compiler#1734]
It seems that the refactoring work of the module naming altered the `--dir` option to name all modules. It would be great if this could default to anonymous modules for formats that support it. Any tips on how this would be done for a PR would be great.

**Comment by johnjbarton** [comment]
`compileAllJsFilesInDir()` does this work.  A test would prevent future regressions.

**Comment by guybedford** [comment]
Thanks, from my initial testing it seems that the `moduleName: false` option isn't working for the main compiler class. Was this API changed?

**Comment by johnjbarton** [comment]
See https://github.com/google/traceur-compiler/commit/9d88d8929309064b10db24a630419704eb45691f
