### ISSUE TITLE
Make spread calls faster

### ISSUE THREAD

**Issue by arv** [google/traceur-compiler#1746]
Given:

```js
f(a, b, ...cs, d, ...es, f)
```

Today we transform that into:

```js
f.apply((void 0), $traceurRuntime.spread([a, b], cs, [d], es, [f]));
```

@caitp has a much better solution for this:

```js
f.apply((void 0), $traceurRuntime.spread(7, a, b, cs, d, es, f, 3, 5));
```

First param is the index where to find the first spread index. Then the trailing indexes are used to tell which params are supposed to be spread. With this approach we have a lot less array allocations.

**Comment by caitp** [comment]
I'm not sure if this is faster, concat() might end up working better. My issue with using arrays was that it made the preparser a bit more complicated, this approach just seemed simpler.

It might be faster though, should measure that :>

**Comment by arv** [comment]
JSPerf says that the existing runtime is faster...

http://jsperf.com/spread-runtime

**Comment by pflannery** [comment]
I always found jsperf (in the past) makes v8 bail so screws the timing.
 
I find ```spread2``` two times faster then ```spread```. 

I created two chrome snippets like this: (I haven't tested firefox yet)

spead snippet
```js
function spread() {
  var rv = [], j = 0, iterResult;

  for (var i = 0; i < arguments.length; i++) {
    var valueToSpread = arguments[i];

    if (typeof valueToSpread[Symbol.iterator] !== 'function') {
      throw new TypeError('Cannot spread non-iterable object.');
    }

    var iter = valueToSpread[Symbol.iterator]();
    while (!(iterResult = iter.next()).done) {
      rv[j++] = iterResult.value;
    }
  }

   return rv;
}

var a = 'a';
var b = 'b';
var cs = ['c1', 'c2'];
var d = 'd';
var es = ['e1', 'e2'];
var f = 'f';


// sanity check
console.log(spread([a, b], cs, [d], es, [f]));

var startedAt = performance.now();
for(var i=0; i<100000; i++) {
  spread([a, b], cs, [d], es, [f])
}

"spread ran 100000 times in "+(performance.now()-startedAt);
```

spread2 snippet
```js
function spread2(spreadIndex) {
  var rv = [];
  var j = 0;
  var endIndex = spreadIndex;
  var length = arguments.length;
  for (var i = 1; i < endIndex; i++) {
    var spread = spreadIndex === length ? endIndex : arguments[spreadIndex];
    for (; i < spread; i++) {
      rv[j++] = arguments[i];
    }

    if (spreadIndex++ === length) break
    var valueToSpread = arguments[i];
    var iter = valueToSpread[Symbol.iterator]();
    while (!(iterResult = iter.next()).done) {
      rv[j++] = iterResult.value;
    }
  }
  return rv;
}

var a = 'a';
var b = 'b';
var cs = ['c1', 'c2'];
var d = 'd';
var es = ['e1', 'e2'];
var f = 'f';

// sanity check
console.log(spread2(7, a, b, cs, d, es, f, 3, 5));

var startedAt = performance.now();
for(var i=0; i<100000; i++) {
  spread2(7, a, b, cs, d, es, f, 3, 5)
}

"spread2 ran 100000 times in "+(performance.now()-startedAt);
```

results:
```js
["a", "b", "c1", "c2", "d", "e1", "e2", "f"]
spread ran 100000 times in 559.041999999783

["a", "b", "c1", "c2", "d", "e1", "e2", "f"]
spread2 ran 100000 times in 292.1290000004228

```

**Comment by pflannery** [comment]
just to add, jsperf is still using Benchmark.js v1.0.0, so unfortunately it is still [buggering v8](http://mrale.ph/blog/2013/08/14/hidden-classes-vs-jsperf.html#adding-things-together). Hopefully jsperf will update when the long awaited Benchmark.js v2.0.0 is final.

**Comment by caitp** [comment]
I'd be more confident from profiling an application which has to use spreadcalls in hot code, but my guess is that that's not something that frequently happens in hot code

**Comment by arv** [comment]
I got

```js
"spread ran 100000 times in 314.72999999823514"
"spread ran 100000 times in 319.0219999960391"
"spread2 ran 100000 times in 342.3400000028778"
"spread2 ran 100000 times in 329.5910000015283"
```

So to me it does no seem worth changing this.

**Comment by pflannery** [comment]
I agree...I just tried Canary with my windows 8.1 and got very similar
