### ISSUE TITLE
ForInTransform produces invalid code in angular's collections facade

### ISSUE THREAD

**Issue by caitp** [google/traceur-compiler#1756]
The code `for (var prop in stringMap) {` produces `for (var prop = void 0 in stringMap) {`, but it's not legal to have an initializer for such a declaration.

In JSC, the result is a SyntaxError if code is in strict mode. https://github.com/WebKit/webkit/blob/16cf88db89bbc38857e0879e621aad19e42c654e/Source/JavaScriptCore/parser/Parser.cpp#L750

It's hard to see where the initializer is added, but it probably should not happen

**Comment by caitp** [comment]
This might be from some of angular's custom transforms, not clear =)

**Comment by caitp** [comment]
https://github.com/google/traceur-compiler/blob/982bf9f235ecc759c2ae8c194cc9597c2d7d84ba/test/unit/codegeneration/BlockBindingTransformer.js#L360-L367 makes it look like either specific flags cause the issue, or it's not traceur's fault

**Comment by johnjbarton** [comment]
Here is a complete example:
https://google.github.io/traceur-compiler/demo/repl.html#var%20stringMap%20%3D%20%7B%7D%3B%0Afor%20(var%20prop%20in%20stringMap)%20%7B%20%7D

**Comment by caitp** [comment]
It affects the angular es5 build, which probably means it's a specific set of flags in traceur that trigger it

**Comment by arv** [comment]
This was fixed pretty recently. https://github.com/google/traceur-compiler/pull/1687

**Comment by johnjbarton** [comment]
I'll push a new version to ghpages.
