### ISSUE TITLE
`export default ...` binding

### ISSUE THREAD

**Issue by caridy** [google/traceur-compiler#1758]
@arv someone was asking about this case:

```js
var f = 1;
export default f;
f = 2;
```

I remember we have discussed this a couple of times, but I don't remember the outcome of those conversations. My interpretation of the spec is that `import value from "./mod"` will set `value` to `2` since the mappings for the ExportEntry Record `[[LocalName]]` will be `"f"`, but I don't think babel or traceur are accounting for this edge case.

**Comment by arv** [comment]
I don't think that is is accurate. This case is the `export default AssignmentExpression` which just evaluates the expression. There is no binding for `f` involved here.
