### ISSUE TITLE
sourceMappingURL present when requesting in-memory source maps

### ISSUE THREAD

**Issue by demerzel3** [google/traceur-compiler#1763]
If you compile with {sourceMaps: 'memory'} shouldn't sourceMappingURL be omitted from the output?
Having sourceMappingURL printed in the output can make it difficult to integrate traceur into e.g. a gulp workflow.
Of course one can always strip it out, but not having it in the first place would be easier. Is the current behavior of {sourceMaps: 'memory'} the intended one?

**Comment by johnjbarton** [comment]
Fixed by #1764
