### ISSUE TITLE
FROM atscript or ES6?

### ISSUE THREAD

**Issue by blakemcbride** [google/traceur-compiler#1768]
I don't get it:

From Traceur site: Traceur is a JavaScript.next-to-JavaScript-of-today compiler

From atscript-playground site:  Traceur Transpiles AtScript code into regular ES5 

Does Traceur start with ES6, Atscript, either, or are they the same?
Thanks for the clarification!
Blake McBride

**Comment by arv** [comment]
Replied on mailing list already
