### ISSUE TITLE
PureES6Transformer does not pass options to transformers

### ISSUE THREAD

**Issue by caitp** [google/traceur-compiler#1774]
This breaks TypeAssertionTransformer, which wants to make use of options if `this.assertionAdded_` is true.

**Comment by johnjbarton** [comment]
Now all we need is a test case or repro steps.

**Comment by caitp** [comment]
I'm sorry, but I don't have specific repro steps. I can tell you that https://github.com/angular/angular/blob/85abfa943d957045379239ccf654fcf04ead9be9/modules/angular2/change_detection.js this file contains the text which causes this.

But you can plainly see why it fails in master. 

1. https://github.com/google/traceur-compiler/blob/0b17757bf299163fc77c676bbb43b6371cc5452d/src/codegeneration/PureES6Transformer.js#L42 << we are calling TypeAssertionTransformer with 2 arguments.
2. https://github.com/google/traceur-compiler/blob/0b17757bf299163fc77c676bbb43b6371cc5452d/src/codegeneration/TypeAssertionTransformer.js#L62 << we are setting `this.options_` to an undefined value.
3. https://github.com/google/traceur-compiler/blob/0b17757bf299163fc77c676bbb43b6371cc5452d/src/codegeneration/TypeAssertionTransformer.js#L233 << an assertion is already added, so we try to check the value of `typeAssertionModule`, thus we get a TypeError trying to dereference a field of undefined.

`({ b: void 0 }).b.c`

**Comment by johnjbarton** [comment]
Sure, but the reason we have this bug is we did not have a test case. Fixing this is easy. Writing a test case -- essential for the fix IMO -- would be much easier if we had a small program that failed.

**Comment by caitp** [comment]
[Here's an example you can try on the repl](https://google.github.io/traceur-compiler/demo/repl.html#%2F%2F%20Options%3A%20--annotations%20--member-variables%20--source-maps%20--type-assertions%20--types%20%0A%2F%2Flet%20foo%3Astring%20%3D%20%22hello%22%3B%0A%0Aclass%20Foo%20%7B%0A%20%20method(str%3Astring)%20%7B%0A%20%20%7D%0A%7D%0A):

```js
// Options: --annotations --member-variables --source-maps --type-assertions --types 
//let foo:string = "hello";

class Foo {
  method(str:string) {
  }
}
```

Just uncomment the first lexical declaration and it will freak out

**Comment by caitp** [comment]
[even simpler one](https://google.github.io/traceur-compiler/demo/repl.html#%2F%2F%20Options%3A%20--annotations%20--member-variables%20--source-maps%20--type-assertions%20--types%20%0Alet%20foo%3Astring%20%3D%20%22hello%22%3B%0A%2F%2Flet%20foo%3Astring%20%3D%20%22bye%22%3B%0A)

**Comment by caitp** [comment]
actually, these are wrong (although reading the parser it looks like it should work). lets see..

**Comment by johnjbarton** [comment]
These examples fail because Traceur inserts a call to global `assert` but
the runtime does not include an implementation.  I think we should name
that function something less common than "assert" and we should include an
implementation in the runtime.

**Comment by caitp** [comment]
the examples don't demonstrate the actual problem. I don't know what the cause of the problem is, but referencing a field of something which is never defined is broken one way or the other

**Comment by caitp** [comment]
A simple test case would just be asserting that `transformer.prependAssertionImport_(dummyParseTree, dummyCtor)` does not throw if `transformer.options_` is undefined, and `transformer.assertionAdded_` is true

**Comment by johnjbarton** [comment]
For some reason the examples disappeared.
```js
// Options: --annotations --member-variables --source-maps --type-assertions --types 
let foo:string = "hello";
//let foo:string = "bye";
```

**Comment by caitp** [comment]
See my above comment, I realized they didn't actually demonstrate the real problem, so I removed them

**Comment by johnjbarton** [comment]
Well it is not possible to set `outputlanguage='es6'` in the `repl.html` so its not surprising that the test case shows another problem.

So we still need a test, via the API or a file and options for the command line.  (BTW the correct fix IMO is to not call the ctor with undefined options rather than guard when against the case of an incorrect call. `prependAssertionImport_` is not API.

**Comment by arv** [comment]
Maybe throw if no option is passed.

I think I can cook up a unit test for this with a fix. Doesn't seem too hard.
