### ISSUE TITLE
Add support for transforming async to a generator

### ISSUE THREAD

**Issue by arv** [google/traceur-compiler#1780]
Since generators are available in Chrome, Firefox and io.js it would be nice to transform async functions to a wrapped generator.

**Comment by arv** [comment]
@mnieper

**Comment by arv** [comment]
Updated description to include Chrome and Firefox

**Comment by mnieper** [comment]
@arv Async generators are transformed into async functions. So all that remains :-) is to rewrite the code handling async functions.

One way to do it would be to make the async function transform a separate transform that happens before the generator transform and that rewrites the async function into a ES6 generator. Then it is up to the generator transform whether it transform the generator or not.
