### ISSUE TITLE
Nested derived classes allow `this` reference before `super()` in parent class

### ISSUE THREAD

**Issue by sebmck** [google/traceur-compiler#1797]
AFAIK the test [feature/Classes/NestedClassSuperAnimal](https://github.com/google/traceur-compiler/blob/master/test/feature/Classes/NestedClassSuperAnimal.js) should be failing as `this` is referenced before `super();` and so it should be throwing `'this' is not allowed before super()`.

I've managed to simplify it to the following:

```javascript
class Roo extends Animal {
  constructor() {
    class Koala extends Animal {
      constructor() {
        super();
      }
    }
    this.a = new Koala;
    super();
  }
}
```

**Comment by arv** [comment]
Yup. The visitor should not traverse into classes.
