### ISSUE TITLE
Sourcemaps line offset when using modules:instantiate

### ISSUE THREAD

**Issue by joIivier** [google/traceur-compiler#1798]
In my build I use traceur with the options `{modules: 'instantiate', moduleName: true}` and the sourceMaps it generates have an offset. I investigated with the following input file:

```
import React from 'react';

import a from 'a';
import b from 'b';
import c from 'c';
import d from 'd';
import e from 'e';
import f from 'f';
import g from 'g';
import h from 'h';
import i from 'i';

class Foo {
  
  // Rendering

  render() {
    console.log('render');
   }
}
```
And the line I will get from the console log (in chromium) would be 42 instead of 18.
I looked at the generated ES5 file and the beginning is:
```
System.register("Foo.js", ["react", "a", "b", "c", "d", "e", "f", "g", "h", "i"], function($__export) {
  "use strict";
  var __moduleName = "Foo.js";
  var React,
      a,
      b,
      c,
      d,
      e,
      f,
      g,
      h,
      i,
      Foo;
  return {
    setters: [function($__m) {
      React = $__m.default;
    }, function($__m) {
      a = $__m.default;
    }, function($__m) {
      b = $__m.default;
    }, function($__m) {
      c = $__m.default;
    }, function($__m) {
      d = $__m.default;
    }, function($__m) {
      e = $__m.default;
    }, function($__m) {
      f = $__m.default;
    }, function($__m) {
      g = $__m.default;
    }, function($__m) {
      h = $__m.default;
    }, function($__m) {
      i = $__m.default;
    }],
    execute: function() {
      Foo = (function() {
        var Foo = function Foo() {};
        return ($traceurRuntime.createClass)(Foo, {
          render: function() {
            console.log('render');

```
And from my handmade computations,  42 is the line of the `console.log('render')` in the ES5 output if the first line is the `System.register` call, but the input file to traceur has `console.log('render')` on the 18th line so I guess all these added lines to create the SystemJS module are not taken into account when computing the sourceMaps.

**Comment by guybedford** [comment]
@joIivier it sounds like the source map is not actually being applied at all for some reason. Ensure that you are getting the correct settings for the `file`, `sourceRoot` and `sources` values in the source map. Here are the settings used internally in SystemJS builder that work for us - https://github.com/systemjs/builder/blob/master/compilers/es6.js#L73, https://github.com/systemjs/builder/blob/master/compilers/es6.js#L86.

**Comment by joIivier** [comment]
Ok so the reason I deduced from your comment is that I needed to add `sourceMaps: true` to my traceur options ^^. I added it and I have no more line offset. Thanks for your quick answer!
