### ISSUE TITLE
Transpiling TypeScript

### ISSUE THREAD

**Issue by djindjic** [google/traceur-compiler#1800]
As it's [announced](https://www.youtube.com/watch?v=QHulaj5ZxbI&list=PLOETEcp3DkCoNnlhE-7fovYvqwVPrRiY7&t=1455) 1/2 day(s) ago, AtScript is now called TypeScript, and does it mean that traceur will transpile TypeScript code and when?

[Here](https://github.com/google/traceur-compiler/issues/771) is still opened comparison issue which doesn't reveal the future. :)

**Comment by OliverJAsh** [comment]
:+1:

**Comment by johnjbarton** [comment]
[The best way to predict the future is to invent it.](http://en.wikiquote.org/wiki/Alan_Kay)
Our guidelines for contributing are here: https://github.com/google/traceur-compiler/blob/master/CONTRIBUTING.md.
