### ISSUE TITLE
Using 'async function (){}' leads to an error

### ISSUE THREAD

**Issue by ComFreek** [google/traceur-compiler#1801]
The following code throws an error [on the REPL Website](http://google.github.io/traceur-compiler/demo/repl.html#var%20a%20%3D%20async%20function%20(parameter)%20%7B%0A%20%20await%20doSomething(parameter)%3B%0A%7D%3B):
```
var a = async function (parameter) {
  await doSomething(parameter);
}
```

> traceured.js:1:15: Semi-colon expected,traceured.js:1:24: Unexpected token (,traceured.js:1:25: Unexpected token parameetr,traceured.js:2:9: Semi-colon expected

**Comment by ComFreek** [comment]
Never mind, I forgot to pass the `--asyncFunctions true` flag to Traceur (and activating experimental mode on the REPL website, respectively).

**Comment by johnjbarton** [comment]
You can set the option the REPL using the "Show All Options" option.

http://google.github.io/traceur-compiler/demo/repl.html#%2F%2F%20Options%3A%20--async-functions%20%0Avar%20a%20%3D%20async%20function%20(parameter)%20%7B%0A%20%20await%20doSomething(parameter)%3B%0A%7D%3B
