### ISSUE TITLE
ASI: insert semicolon when multiline comment occurs, too.

### ISSUE THREAD

**Issue by caitp** [google/traceur-compiler#1803]
These bug titles are wordy and hard to file =)

There's an ASI bug in v8, spidermonkey, and TypeScript which I noticed today, but apparently Traceur does okay with it --- with the exception that it doesn't deal with the line-feed before `=>` if it occurs in a multi-line comment.

This is inconsistent with the way ASI rules work in browsers, so it's probably not what you want

**Comment by caitp** [comment]
This actually seems to be wrong in general, not just in arrow functions.

```js
x: for (var i = 0; i < 100; ++i) {
  y: for (var j = 0; j < 100; ++j) {
    console.log("y" + j);
    break /*
      */ x;
  }
  console.log("x" + i);
}
```

is translating to

```js
x: for (var i = 0; i < 100; ++i) {
  y: for (var j = 0; j < 100; ++j) {
    console.log("y" + j);
    break x;
  }
  console.log("x" + i);
}
```

which is inconsistent with browsers

**Comment by arv** [comment]
Really? That makes no sense to me. I have to dig through the spec for this.

**Comment by zenparsing** [comment]
A better test case:

```js
function f() {
  return /*
    */ 1;
}
f();  // Should be undefined, according to the spec
```

It's called out explicitly at http://people.mozilla.org/~jorendorff/es6-draft.html#sec-lexical-and-regexp-grammars, second paragraph.

> A MultiLineComment (that is, a comment of the form “/*…*/” regardless of whether it spans 
> more than one line) is likewise simply discarded if it contains no line terminator; but if 
> a MultiLineComment contains one or more line terminators, then it is replaced by a single 
> line terminator, which becomes part of the stream of input elements for the syntactic grammar.

**Comment by caitp** [comment]
Thanks for finding the paragraph to cite, I was looking for it but couldn't find one

**Comment by arv** [comment]
Thanks Kevin.
