### ISSUE TITLE
commander@2.7.0 breaks traceur CLI

### ISSUE THREAD

**Issue by soareschen** [google/traceur-compiler#1804]
Traceur depends on [commander](https://www.npmjs.com/package/commander), which was updated yesterday from 2.6.0 to 2.7.0. This breaks the traceur CLI with error message `Error: At least one input file is needed` regardless of the input.

To reproduce, simply `npm install traceur` fresh. If `commander@2.6.0` is installed before Traceur is installed, the CLI would work properly.

**Comment by arv** [comment]
I guess we should just hard code the version then.
