### ISSUE TITLE
static member variable causes Unexpected token ;

### ISSUE THREAD

**Issue by pflannery** [google/traceur-compiler#1822]
the following code causes a ```Unexpected token ;``` error when running the code
```js
// Options: --member-variables
class Test {
 static myVar = 0; 
}
```
translates to
```js
$traceurRuntime.ModuleStore.getAnonymousModule(function() {
  "use strict";
  var Test = function Test() {
    ; // ERROR HERE
  };
  ($traceurRuntime.createClass)(Test, {}, {myVar: 0});
  return {};
});
```

The error is on line 4, [REPL here](https://google.github.io/traceur-compiler/demo/repl.html#%2F%2F%20Options%3A%20--member-variables%0Aclass%20Test%20%7B%0A%20static%20myVar%20%3D%200%3B%20%0A%7D)

**Comment by caitp** [comment]
Which browser is this a syntax error in?

**Comment by pflannery** [comment]
oops I was missing the ```--member-variables``` option in the code and then I saw this in the REPL and thought this was why..my bad.

**Comment by caitp** [comment]
An empty statement is emitted though --- which is kind of weird and does not represent the actual code ;) The empty statement is where member variable initializers __would__ go, if there were any

**Comment by pflannery** [comment]
:+1:  thanks folks
