### ISSUE TITLE
Invalid Syntax

### ISSUE THREAD

**Issue by guybedford** [google/traceur-compiler#1828]
Just had an issue caused by this syntax:

```javascript
for (var prop = void 0 in primitives) {
  assert.type[prop] = primitives[prop];
}
```

Not parsing in Traceur when it parses in browsers.

Is it valid? Does Traceur aim to support anything that a browser would?

**Comment by caitp** [comment]
it's not technically valid syntax. it's erroneously allowed in v8 all the time, and is disabled only in strict mode in JSC for compat with legacy code.

**Comment by arv** [comment]
I thought this was fixed. @guybedford What version are you seeing this in? Can you provide a test case?

**Comment by caitp** [comment]
The thing that was fixed was traceur outputting that syntax. Bug is about it not parsing that

**Comment by arv** [comment]
I see. ES6 does not allow that. It is one of the known intended incompatibilities.

http://people.mozilla.org/~jorendorff/es6-draft.html#sec-additions-and-changes-that-introduce-incompatibilities-with-prior-editions

> 13.6: Prior to Edition 6, an initialization expression could appear as part of the VariableDeclaration that precedes the in keyword. The value of that expression was always discarded. In Edition 6, the ForBind in that same position does not allow the occurrence of such an initializer.
