### ISSUE TITLE
How is Traceur pronounced?

### ISSUE THREAD

**Issue by rauschma** [google/traceur-compiler#1875]
Options (among others):

1. tray-SOOR
2. truh-SOOR
3. TRAY-ser

**Comment by domenic** [comment]
From http://dictionary.reference.com/browse/traceur, pronounced /træˈsɜː/

**Comment by rauschma** [comment]
If you google for “define traceur”, you get two options:

* ˈtreɪsə
* traˈsəː

I’m mainly wondering whether any of these is officially “blessed”.

**Comment by arv** [comment]
The intent is the french pronunciation... not sure I pronounce it right though.

**Comment by rauschma** [comment]
Cool! truh-SIR comes closest (ideally with a French R, with a British R being better than an American R).

**Comment by pflannery** [comment]
I've been saying it like this https://www.youtube.com/watch?v=VLCeLzl-1y4  and always enjoy the French twang ;)

**Comment by UltCombo** [comment]
I always thought it was close to "tray-sor", oh well.

**Comment by mariusschulz** [comment]
… and what do we learn about this? Choose easily pronounceable names for your projects. ;)

**Comment by rauschma** [comment]
@mariusschulz: but it is – for French people. ;-)

For me, names being web-searchable trumps ease of pronunciation. For example, I’m slightly unhappy that Facebook chose such generic names for some of their projects: e.g. React and Flow.

**Comment by johnjbarton** [comment]
Or...create a project so cool people want to know how to pronounce its name
correctly ;-)

**Comment by mariusschulz** [comment]
@rauschma: Go, Hack, … the list goes on. :P

Product names should primarily be easy to googlebing, I agree, however unambiguous naming facilitates oral communication.

**Comment by fvsch** [comment]
I find "traceur" quite easy to pronounce. Just say « traceur ». :smile:

French pronunciation is /tʀasœʀ/. The first vowel is similar to the one in “hat” in British Received Pronunciation, and the second one has no equivalent in English so you're out of luck I guess (but [see if you can find something you know here](https://en.wikipedia.org/wiki/Open-mid_front_rounded_vowel)). Also I know that some pronunciation guides say that the stress is on the final syllable, but just try not to stress it too much (or at all, really), the resulting "traCEEEUUUR" would sound bizarre.

Maybe I should go around the office and record people saying « traceur ».

Also there is no such thing as unambiguous pronunciation. As any native English speaker can tell from hearing non-native coders say the "English" names of most technologies.

**Comment by mariusschulz** [comment]
You'll always hear people pronounce English words differently, depending on their dialect or accent. Even non-native listeners can confirm that. ;)

What I'm trying to argue, though, is that some terms are more difficult in general than others. Microsoft Azure was one of those, and so is Traceur. It's not immediately obvious whether a French or English pronunciation is intended.

Anyway, we've got the answer now. :)

**Comment by sylvainpolletvillard** [comment]
Ha, that is funny to read as a French speaker :) By now, we are accustomed to pronounce all kind of software names in English (like "TaïpeSkwipt" for TypeScript). It is amusing to see that conversely English speakers are so confused while it seems natural to us.

So to make things clear :
- we do not stress one syllab or another, this is English stuff. When we stress some parts of a sentence, that is emotional, not linguistical.
- the "a" of Traceur sounds like "hat" or the second one in "banana"
- the "eu" sounds like the "u" in "buddy"
- the "r" is quite difficult to explain to English speakers, as much as "the" is to French speakers . See : https://www.youtube.com/watch?v=TPoLgwfWjZ4
- do not listen to Google Translate French pronounciation as it is horrible.
