### ISSUE TITLE
Uncaught SyntaxError: Unexpected reserved word when Transpiling

### ISSUE THREAD

**Issue by mohanr** [google/traceur-compiler#1898]
My index.html is this.
  
```html
  <script src="app.js"></script>
<script src="traceur.js"></script>
<script src="view1/view1.js"></script>
<script src="view2/view2.js"></script>
<script src="components/version/version.js"></script>
<script src="components/version/version-directive.js"></script>
<script src="components/version/interpolate-filter.js"></script>
<script>
  $traceurRuntime.options.experimental = true;
  new traceur.WebPageTranscoder(document.location.href).run();
</script>
```

My app.js is this

```js
'use strict';

// Declare app level module which depends on views, and components
angular.module('myApp', [
  'ngRoute',
  'myApp.view1',
  'myApp.view2',
  'myApp.version'
]).
config(['$routeProvider', function($routeProvider) {
  $routeProvider.otherwise({redirectTo: '/view1'});
}]);
export var test = 'es6!';
```

I may be missing something but this does not transpile ?
Uncaught SyntaxError: Unexpected reserved word

**Comment by caitp** [comment]
Use some backticks so that folks can read your example =) https://help.github.com/articles/markdown-basics/#multiple-lines

**Comment by arv** [comment]
@mohanr `export` is only allowed in `Module`. Based on the information you provided it is not clear how you import app.js?

**Comment by johnjbarton** [comment]
@mohanr, which version are you using?  I just landed a change to `WebPageTranscoder`.

Which line and file is the error reported on?   Is this error in the chrome devtools console?

**Comment by mohanr** [comment]
traceur@0.0.88
@arv I just added one line 'export var test = 'es6!';' to check. Everything else is the older style.

**Comment by mohanr** [comment]
I have changed it like this now. But I see the same error.
app.js

```
'use strict';

// Declare app level module which depends on views, and components
angular.module('myApp', [
  'ngRoute',
  'myApp.view1',
  'myApp.view2',
  'myApp.version'
]).
config(['$routeProvider', function($routeProvider) {
  $routeProvider.otherwise({redirectTo: '/view1'});
}]);
import {test} from './module';
console.log(test);
```

module.js
```
export var test = 'es6!';
```

**Comment by johnjbarton** [comment]
Your `app.js` is not loaded by your `index.html` so there is no way for us to help you.

My guess is that `app.js` is not going through traceur at all.

It only makes sense to use the `WebPageTranscoder` if you set `type="module"` on your `<script>` tags.

**Comment by mohanr** [comment]
```
  <script src="bower_components/angular/angular.js"></script>
  <script src="bower_components/angular-route/angular-route.js"></script>
  <script type="module" src="app.js"></script>
  <script src="traceur.js"></script>
  <script type="module" src="view1/view1.js"></script>
  <script type="module" ="view2/view2.js"></script>
  <script src="components/version/version.js"></script>
  <script src="components/version/version-directive.js"></script>
  <script src="components/version/interpolate-filter.js"></script>
```

I am loading app.js.
Should it be like this ?

**Comment by arv** [comment]
It is not clear to me what is going on here?

One thing to keep in mind is that script[type=module] is async (and we do not enforce the order) so if there are dependencies between those scripts you will run into trouble.

**Comment by johnjbarton** [comment]
This looks like a bug in the (poorly tested) web transcoder related to recent changes in eg `BrowserTraceurLoader`.
