### ISSUE TITLE
yield without expr has issues

### ISSUE THREAD

**Issue by arv** [google/traceur-compiler#1899]
The following statements have issues

```js
function* g() {
  var x = {yield};
  return yield;
}
```

**Comment by zenparsing** [comment]
Should the first statement work?

It seems `var x = {yield};` should fail since "yield" is not allowed as an identifier in generator functions, and shorthand properties must be identifier references:

```js
PropertyDefinition[Yield] :
    IdentifierReference[?Yield]
```

**Comment by arv** [comment]
@zenparsing You are right. `{yield}` should be a syntax error.

**Comment by msmhrt** [comment]
Hi all,

The following code isn't valid too?

```
(function() {
    "use strict";

    let fn = () => {};

    function* testYield() {
        fn(yield);
    }

    testYield().next();
}());
```

**Comment by msmhrt** [comment]
[PEP 342](https://www.python.org/dev/peps/pep-0342/) of Python  says `foo(yield 42)` and `foo(yield)` are legal, but Python 3.4.2 raises "SyntaxError: invalid syntax".
This isn't a Python's bug. Please see [Issue 20330](http://bugs.python.org/issue20330) of Python tracker.

**Comment by zenparsing** [comment]
@msmhrt That example should parse fine.

**Comment by msmhrt** [comment]
Should I report that example as new issue?

**Comment by arv** [comment]
@msmhrt No need to file another bug.
