### ISSUE TITLE
Register format name consolidation

### ISSUE THREAD

**Issue by guybedford** [google/traceur-compiler#1915]
Ideally the `instantiate` format would be called the `register` format.

Do you think there will be any chance of consolidation here in future?

**Comment by arv** [comment]
I agree. The naming is confusing now.

**Comment by guybedford** [comment]
Thanks, is there any chance the `register` format name will free up at some point in future do you think?

**Comment by guybedford** [comment]
Posted https://github.com/google/traceur-compiler/pull/1916.
