### ISSUE TITLE
CloneTreeTransformer?

### ISSUE THREAD

**Issue by johnjbarton** [google/traceur-compiler#1923]
Looks like this class is not used any more. It increases our test time. Is it still needed?

**Comment by arv** [comment]
I found a bug thanks to it today.

It is being used by the feature tests to make sure our writer/parser round
trips correctly.

We spent a lot of time improving the performance of the parser but we
haven't even tried optimizing the transformers. Maybe we should focus on
that to get the test time down.

On Tue, May 5, 2015 at 11:36 AM, johnjbarton <notifications@github.com>
wrote:

> Looks like this class is not used any more. It increases our test time. Is
> it still needed?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/google/traceur-compiler/issues/1923>.
>



-- 
erik
