### ISSUE TITLE
Wrong assignment in await statements

### ISSUE THREAD

**Issue by arcanis** [google/traceur-compiler#1934]
The following code doesn't work (cf [repl](http://google.github.io/traceur-compiler/demo/repl.html#%2F%2F%20Options%3A%20--annotations%20--array-comprehension%20--async-functions%20--async-generators%20--exponentiation%20--export-from-extended%20--for-on%20--generator-comprehension%20--member-variables%20--proper-tail-calls%20--require%20--source-maps%20--symbols%20--types%20%0A%0Aasync%20function%20test()%20%7B%0A%20%20return%20await%20new%20Promise(%20(%20resolve%2C%20reject%20)%20%3D%3E%20%7B%0A%0A%20%20%20%20%20%20let%20escapedQuery%20%3D%20%22test%22.replace(%20%2F%5B%5C%5C%26%7C!()%7B%7D%5B%5C%5D%5E%22~*%3F%3A%2B-%5D%2Fg%2C%20'%5C%5C%241'%20)%3B%0A%20%20%20%20%20%20alert(%20escapedQuery%20)%3B%0A%0A%20%20%7D%20)%3B%0A%7D%0A%0Atest()%0A)). It alerts the function replace instead of the result of the function call.

```js
async function test() {
  return await new Promise( ( resolve, reject ) => {

      let escapedQuery = "test".replace( /[\\&|!(){}[\]^"~*?:+-]/g, '\\$1' );
      alert( escapedQuery );

  } );
}

test()
```

**Comment by arv** [comment]
The explode transformer is failing to add parens.

What we have now is:

```js
var x = expressionThatNeedsToBeExpanded;
```

which gets turned into:

```js
var x = a, remainder;
```

we need to ensure that we get:

```js
var x = (a, remainder);
```

**Comment by arv** [comment]
Actually, the problem is that we should not expand the function body (or params).

There are other bugs related to missing parens but not for generators/async functions.
