### ISSUE TITLE
I don't know what's wrong.

### ISSUE THREAD

**Issue by yyjazsf** [google/traceur-compiler#1943]
dose not work~

<h3>用时<span id="spendTime"></span></h3>
<script src="http://google.github.io/traceur-compiler/bin/traceur.js"></script>

<script>
    $traceurRuntime.options.symbols = true;
</script>
<script>
    var t1=+new Date;
</script>
<script type="module">
    "use strict";
    class Test {
        test() {
            return "test";
        }
    }
    var test = new Test;
    // "test"
    console.log(test.test());
    var t2=+new Date();
    document.getElementById('spendTime').innerText=''+(t2-t1);
</script>

**Comment by creamidea** [comment]
我遇到了和你一样的问题，我把```<script type="module">```变成```<script>``` 。去掉了type属性就可以了。你可以试试。
