### ISSUE TITLE
Older version of WebKit does not have Function.prototype.bind defined in ECMAScript 5.1...

### ISSUE THREAD

**Issue by oksurf** [google/traceur-compiler#1945]
Traceur is supposed to translate to ECMAScript 5. Function.prototype.bind is only standard in "ECMAScript 5.1 (ECMA-262) The definition of 'Function.prototype.bind' in that specification."

I'm able to use a polyfill but if Traceur is truly generating ECMAScript 5 then it should not count on this being available in the browser. I'm using a custom "corporate" Qt version of Webkit...

**Comment by arv** [comment]
Not true. bind is part of ES5. 5.1 is just an errata of 5.

Try this: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/bind#Polyfill

**Comment by oksurf** [comment]
Yes the polyfill works, just thought you might add that to traceur in case it is not defined, would save hassle for other ECMAScript5 browsers that did not implement the errata 5.1?

**Comment by UltCombo** [comment]
Erratas do not add any new functionality. @arv has already said it, `Function#bind` is part of ES5, not ES5.1.
