### ISSUE TITLE
Is Traceur going to be discontinued?

### ISSUE THREAD

**Issue by AlicanC** [google/traceur-compiler#1950]
Since Google abandoned AtScript and teamed up with Microsoft to work on TypeScript and Angular 2 is being coded in TypeScript, I would assume that Google will put a lot of effort to make TypeScript great.

Some differences between TypeScript and Traceur are listed in #771, but if we look at Traceur's experimental features (mostly "types") and TypeScript's roadmap (mostly "ES6 compliance"), it looks like we won't see much difference between Traceur and TypeScript in the future. (Besides TypeScript probably being better since it's backed by not one giant company, but two.)

That being said, is there a solid reason to continue developing Traceur? Wouldn't it be better to announce discontinuation and direct people to TypeScript?

**Comment by johnjbarton** [comment]
We want to work on Traceur. That is all the reason we need.

**Comment by AlicanC** [comment]
Sure.

**Comment by arv** [comment]
@AlicanC Traceur has a long history. It just happened that our path aligned with the Angular team for a few months in 2014.

**Comment by AlicanC** [comment]
It's not like I need you to kill this project or follow the Angular team to death.

Maybe I am following the wrong feeds, but I am not hearing a lot of cool stuff about Traceur lately. Maybe you were discussing the same thing behind the scenes, maybe not. Who knows?

If you think that Traceur has a reason to go on, go on. Meanwhile, this issue can serve as a "suspicion cleanser" for people who were suspecting a discontinuation.
