### ISSUE TITLE
Regression concerning arrow functions

### ISSUE THREAD

**Issue by johsin18** [google/traceur-compiler#1962]
In Traceur 0.89, the following code

        this._observer = {
            onDChanged: (uuid, d) => {
                if (this.downStreamObserver)
                    this.downStreamObserver.onDChanged(uuid, d);
                this.onChanged();
            },

was compiled to this working code

      this._observer = {
        onDChanged: ($__5 = this, function(uuid, d) {
          if ($__5.downStreamObserver)
            $__5.downStreamObserver.onDChanged(uuid, d);
          $__5.onChanged();
        }),

However, starting from 0.90, some extra parentheses are gone...

    this._observer = {
        onDChanged: $__5 = this, function(uuid, d) {
          if ($__5.downStreamObserver)
            $__5.downStreamObserver.onDChanged(uuid, d);
          $__5.onChanged();
        },

which completely breaks the code, as onDChanged is basically set to "this" instead of the function intended.

**Comment by arv** [comment]
Sorry about the regression :'(
