### ISSUE TITLE
TypeError: Cannot read property 'transform' of undefined

### ISSUE THREAD

**Issue by errorx666** [google/traceur-compiler#1970]
I receive `TypeError: Cannot read property 'transform' of undefined` when trying to compile any code that follows this pattern:

```
while( true ) {
    let foo = 1;
    ( () => { foo; } )();
}
```

It seems to involve the following components:

1. `while` loop (`for` loops seem unaffected)
2. variable declared within loop using either `let` or `const` (`var` is fine)
3. variable created in `2` is referenced inside a closure within the loop

I understand this code might be buggy or bad practice, but the error from Traceur is cryptic.

I am compiling using traceur v0.0.90 via grunt-traceur v0.5.4.

**Comment by errorx666** [comment]
Wow!  You fixed that fast!

**Comment by arv** [comment]
...because I'm addicted to the "Wow!"s
