### ISSUE TITLE
Repeated 'use strict' statements in generated code

### ISSUE THREAD

**Issue by dar5hak** [google/traceur-compiler#1973]
Let's say I have an ES6 file with a global 'use strict' statement. The transpiled file ends up with two global 'use strict' statements.

I'm using [gulp-traceur](https://github.com/sindresorhus/gulp-traceur) with Node 0.10.

**Comment by arv** [comment]
Why would you ever put `"use strict"` at the top of a module file?

**Comment by dar5hak** [comment]
@arv I wouldn't, but just happened to notice this effect while accidentally transpiling an already transpiled file.
