### ISSUE TITLE
Assigning an arrow function to a member of a derived class assigns this instead

### ISSUE THREAD

**Issue by phistuck** [google/traceur-compiler#1989]
Test case -
```
class Bar {
}

class Foo extends Bar
{
	constructor()
	{
		super();
		this.callback = evt =>
		{
			this.baz = 1;
		};
		setTimeout(this.callback);
	}
}
new Foo();
```

Throws an exception, because `this.callback` is actually `this` which results in `setTimeout("[object Object]")` instead of the actual function.

**Comment by arv** [comment]
Fixed by #1988

**Comment by phistuck** [comment]
Thank you! When will the REPL page be updated, then?
https://google.github.io/traceur-compiler/demo/repl.html#class%20Bar%20%7B%0A%7D%0A%0Aclass%20Foo%20extends%20Bar%0A%7B%0A%20%20%20%20constructor()%0A%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20super()%3B%0A%20%20%20%20%20%20%20%20this.callback%20%3D%20evt%20%3D%3E%0A%20%20%20%20%20%20%20%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20this.baz%20%3D%201%3B%0A%20%20%20%20%20%20%20%20%7D%3B%0A%20%20%20%20%20%20%20%20setTimeout(this.callback)%3B%0A%20%20%20%20%7D%0A%7D%0Anew%20Foo()%3B

**Comment by arv** [comment]
I'll try to get a new version pushed soonish

@johnjbarton FYI

**Comment by phistuck** [comment]
Great! Thank you. :)

**Comment by johnjbarton** [comment]
Unfortunately
   Feature Tests Symbol Object.js:
fails for me on master.

**Comment by johnjbarton** [comment]
The test fails because object[s] is enumerable and the loop at the bottom of the file uses 'in'.
https://github.com/google/traceur-compiler/blob/master/test/feature/Symbol/Object.js#L28

Probably something to do with "native" Symbols.

**Comment by arv** [comment]
@johnjbarton Which version of node/chrome?

**Comment by johnjbarton** [comment]
node -v
v0.10.38

**Comment by arv** [comment]
I was using node 4.1.1. Lets just disable the test for now.

**Comment by johnjbarton** [comment]
@phistuck please try again, I updated the server and your case works.

**Comment by phistuck** [comment]
Great, it works. :)
