### ISSUE TITLE
publish to npm script is broken

### ISSUE THREAD

**Issue by arv** [google/traceur-compiler#2070]
I tried to run `npm run just-publish` and I ran into a lot of trouble.

- "pre-" needs to be "pre" in package.json
- build/printSemver.js no longer exists.

I tried a couple of things and the npm version is increased...

I should have realized that I could have used `npm publish --dry-run` earlier to prevent all these spurious version updates.

**Comment by johnjbarton** [comment]
Sorry about that, our publish is pretty dicey. I'm not sure my improvements were...
At least in part this is a side-effect of my fix for #2054.

**Comment by johnjbarton** [comment]
I gather that you did publish to npm to push the version number up to 0.0.100.  Unfortunately now `npm install traceur` fails with `Refusing to install traceur as a dependency of itself`. I'll try to sync it back up.

**Comment by arv** [comment]
Sorry, I had to bump the version to get the script through... but I should have used `--dry-run` from the start. Lesson learned.

**Comment by johnjbarton** [comment]
I am not able to `make clean` because `npm install` fails.   

We depend upon chai, chai has a dev dep on karma, karma fails
```
208 error code EPEERINVALID
209 error peerinvalid The package karma@0.12.37 does not satisfy its siblings' peerDependencies requirements!
209 error peerinvalid Peer karma-phantomjs-launcher@0.1.1 wants karma@>=0.9
210 verbose exit [ 1, true ]
```

**Comment by johnjbarton** [comment]
`npm run just-publish` seems to work.
