### ISSUE TITLE
export default self-invoking function

### ISSUE THREAD

**Issue by guybedford** [google/traceur-compiler#2083]
The following is not supported in Traceur but is supported in Babel as a self-invoking function:

```javascript
export default function() {
}();
```

This is causing issues because I'm piping the output of Babel to Traceur, where Babel will remove any enclosing brackets from `export default (function() {})()` to look like the above causing the error to be throw in Traceur.

Which is right by the spec?

**Comment by UltCombo** [comment]
IIRC `export default function() {}` exports a function declaration that does not introduce a referenceable binding, while `export default (function() {})` exports a function expression.

**Comment by arv** [comment]
The spec is clear about this. `export default function() {}` is a complete `ExportDeclaration`.

**Comment by guybedford** [comment]
The question here was specifically whether 'export default function() {}()'
with trailing brackets is a self-invoking function or not?

**Comment by arv** [comment]
The answer is not. It is a syntax error.

**Comment by UltCombo** [comment]
Just adding some references to my previous comment.

As per `NOTE` in [ES2016 draft § 14.1.20 Runtime Semantics: InstantiateFunctionObject](https://tc39.github.io/ecma262/#sec-function-definitions-runtime-semantics-instantiatefunctionobject):

> An anonymous *FunctionDeclaration* can only occur as part of an **export default** declaration.

As per [§ 15.2.1.16 Source Text Module Records—Table 43 (Informative): Export Forms Mappings to ExportEntry Records](https://tc39.github.io/ecma262/#table-42), an exported anonymous FunctionDeclaration gets a local name ("binding") of `*default*`, which is not a valid identifier and thus unaccessible from user code.

**Comment by UltCombo** [comment]
@guybedford Babel removing the grouping operator on `export default (function() {})()` looks like a bug to me, that breaks the negative lookahead assertion in [§ 15.2.3 Exports—Syntax—ExportDeclaration](https://tc39.github.io/ecma262/#prod-ExportDeclaration): `export default [lookahead ∉ { function, class }] AssignmentExpression[In] ;`.

**Comment by guybedford** [comment]
@UltCombo thanks so much for the confirmation, I've posted a Babel issue at https://phabricator.babeljs.io/T7136.
