### ISSUE TITLE
Unexpected token Exception when compiling multiple imports

### ISSUE THREAD

**Issue by naorye** [google/traceur-compiler#2096]
I am running the following code:

```
const filePath = 'my-file.js';
var fs = require('fs');
var contents = fs.readFileSync(filePath, 'utf8');

var Compiler = require('traceur').NodeCompiler;
var compiler = new Compiler({ modules: 'commonjs', sourceMaps : 'inline' });
var result = compiler.compile(contents, filePath, filePath);

console.log('success');
```
The content of `my-file.js` is:
```
import modalMethods, { frameLoadTriggerMethods } from 'common/frames/modal/methods';
export default 1;
```
I am getting the following exceptions:
```
my-file.js:1:20: Unexpected token ,
my-file.js:1:22: Unexpected token {
my-file.js:1:24: Semi-colon expected
my-file.js:1:48: Unexpected token }
my-file.js:1:50: Semi-colon expected
my-file.js:1:55: Semi-colon expected
```
common/frames/modal/methods' looks like this:
```
const triggerHostClick = 'triggerHostClick';

export default [
	triggerHostClick
];

export var frameLoadTriggerMethods = [
    openRepliesModal
];
```
What is wrong?

**Comment by arv** [comment]
This works for me. What version of Traceur are you using?

http://google.github.io/traceur-compiler/demo/repl.html#import%20modalMethods%2C%20%7B%20frameLoadTriggerMethods%20%7D%20from%20'common%2Fframes%2Fmodal%2Fmethods'%3B%0Aexport%20default%201%3B

**Comment by naorye** [comment]
I am using es6ify which uses traceur 0.0.79.
Is this the issue?

**Comment by arv** [comment]
0.0.79 was released on Dec 3, 2014 https://github.com/google/traceur-compiler/releases/tag/0.0.79
That import syntax was added on Apr 1, 2015 https://github.com/google/traceur-compiler/commit/005f111f5caace2f3f55eb07759601c8c80fd02d

If you can't/don't want to upgrade you can change your code to:

```js
import {default as modalMethods, frameLoadTriggerMethods } from 'common/frames/modal/methods';
```

or

```js
import modalMethods from 'common/frames/modal/methods';
import { frameLoadTriggerMethods } from 'common/frames/modal/methods';
```
