### ISSUE TITLE
traceur is breaking my typeof tests

### ISSUE THREAD

**Issue by excenter** [google/traceur-compiler#2135]
I have a simple line of code 
`      } else if ( typeof id == 'object'){`
which when run through `.pipe(traceur())` twice is mangled into 
`      } else if ((typeof id === 'undefined' ? 'undefined' : $traceurRuntime.typeof(id)) == 'object') {`
which give me *$traceurRuntime is not defined* whenever it's run in the browser.

**Comment by excenter** [comment]
it also happens if run through once.

**Comment by excenter** [comment]
To clarify, we use Traceur as a gulp task before publishing, and including an entire runtime because traceur has different ideas about typeof comparisons is bananas. 
Are there options/flags we can use so that it doesn't call for the traceurRuntime?

**Comment by UltCombo** [comment]
Disable the `symbols` option when compiling. https://github.com/google/traceur-compiler/wiki/Options-for-Compiling

http://google.github.io/traceur-compiler/demo/repl.html#%2F%2F%20Options%3A%20--symbols%3Dfalse%0A%0Atypeof%20foo

**Comment by arv** [comment]
Thanks @UltCombo

**Comment by excenter** [comment]
http://google.github.io/traceur-compiler/demo/repl.html#%2F%2F%20Options%3A%20--symbols%3Dfalse%0Aif%20(%20typeof%20id%20%3D%3D%20'object')%7B%0A%0A%7D

it works in that format, but how does one pass an option to traceur in gulp? 
the only reference on the npm page is "traceur([options])"
