### ISSUE TITLE
Use with Closure compiler

### ISSUE THREAD

**Issue by karlbateman** [google/traceur-compiler#2138]
The output from traceur is not going through closure. Namely, it's the `"use strict"` prepended to every file.

I am essentially using gulp and piping the output from traceur to closure. Not sure if this is necessary but a reason to use one and not the other would be great 😄 

Any insight would be greatly appreciated.

**Comment by miodrag-manic-rs** [comment]
Don't understand, what you understand... it does not matter :)
It is necessary to make your application, to working on older browsers (IE9, Firefox 3, Opera 9.5).  Beginning of a script, it has global scope (all code in the script will execute in strict mode)

http://www.ecma-international.org/ecma-262/5.1/#sec-10.1.1

**Comment by arv** [comment]
This is required. You should be able to configure closure compiler to accept that.
