### ISSUE TITLE
Arrow functions are parsed incorrectly

### ISSUE THREAD

**Issue by arv** [google/traceur-compiler#457]
The following should be a SyntaxError

``` js
var x = (y) => { return this.x }.bind({x: 10})
```

The BNF is:

```
AssignmentExpression :
  ArrowFunction
```

So the above assignment expression is done with the `}`.

**Comment by bergus** [comment]
Not sure whether this changed since 2013? Current spec: http://www.ecma-international.org/ecma-262/6.0/#sec-assignment-operators
At least, Babel disagrees, and parses the above without any errors. Also I guess `var x = () => { return … }();` is the same?

**Comment by arv** [comment]
@bergus That should be a SyntaxError.
