### ISSUE TITLE
file extension default

### ISSUE THREAD

**Issue by mvolkmann** [google/traceur-compiler#847]
I would like to make traceur part of my project build process (currently using Grunt). There are two parts to this.
1) Run jshint with the esnext option on all files that contain ES6 syntax.
2) Run traceur on all files that contain ES6 syntax to generate ES5 code.

It is inconvenient that the traceur command automatically assumes a ".js" extension for files that don't have it. I would like to mark the files with ES6 syntax by giving them an extension of ".es6". Then I could easily accomplish the steps above because it would be obvious which files need to be processed. Putting the ES6 files in a separate directory from ES5 files is a less desirable solution.

Step 2 would be accomplished with something like this.
traceur --script "scripts/{some-name}.es6" --out "build/scripts/{some-name}.js}"

**Comment by bottleofwater** [comment]
For what it worth, Babel now support class properties since [5.0.0](http://babeljs.io/blog/2015/03/31/5.0.0/), since they are discussed [there](https://gist.github.com/jeffmo/054df782c05639da2adb).

**Comment by arv** [comment]
@bottleofwater FWIW, we readded class properties in October and we had it back in 2012.

**Comment by bottleofwater** [comment]
Oh, indeed, thanks! [(if someone wonders how to use them)](http://google.github.io/traceur-compiler/demo/repl.html#%2F%2F%20Options%3A%20--member-variables%20%0Aclass%20Foo%20%7B%0A%20%20static%20x%20%3D%201%3B%0A%20%20y%20%3D%202%3B%0A%7D%0A)
