### ISSUE TITLE
Implement async arrow functions

### ISSUE THREAD

**Issue by arv** [google/traceur-compiler#992]
As mentioned in #977 we do not yet support async arrow functions.

**Comment by mgenev** [comment]
what is the status on this? can we use async arrow functions?

**Comment by arv** [comment]
I closed it because it was fixed.

http://google.github.io/traceur-compiler/demo/repl.html#%2F%2F%20Options%3A%20--async-functions%0A%0Alet%20f%20%3D%20async%20()%20%3D%3E%20%7B%0A%20%20await%2042%3B%0A%7D%3B%0A%0Alet%20g%20%3D%20async%20x%20%3D%3E%20%7B%0A%20%20await%2042%3B%0A%7D%3B
